version: "3"

services:
  caddy:
    container_name: caddy
    image: caddy:2.6.4-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./log:/var/log/caddy
      - caddy_data:/data
    restart: unless-stopped
    environment:
      - MINIKUBE_IP=${MINIKUBE_IP}
      - KOURIER_PORT=${KOURIER_PORT}
      - DASHBOARD_PORT=${DASHBOARD_PORT}

volumes:
  caddy_data:
