apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-cold-0
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "5000"

        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "1"

        autoscaling.knative.dev/window: "6s"
    spec:
      containers:
        - image: dev.local/fibonacci:1.0.0
          resources:
            requests:
              cpu: 100m
              memory: 256M
            limits:
              cpu: 1
              memory: 512M
