apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-n-pod-six
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "9999"

        autoscaling.knative.dev/min-scale: "6"
        autoscaling.knative.dev/max-scale: "6"

        autoscaling.knative.dev/window: "30s"

        autoscaling.knative.dev/target-burst-capacity: "-1"
    spec:
      containers:
        - image: dev.local/fibonacci:1.0.0
          resources:
            requests:
              cpu: 0.16
              memory: 512M
            limits:
              cpu: 0.16
              memory: 512M
