apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fibonacci-single-unit
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "2000"

        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"

        # Stable window
        autoscaling.knative.dev/window: "30s"

        autoscaling.knative.dev/target-burst-capacity: "0"

        # If current concurrency is x% of target, scale up (accommodate containerCreating)
        # autoscaling.knative.dev/target-utilization-percentage: "50"

        # # Make 3 pods when scaling from zero
        # autoscaling.knative.dev/activation-scale: "1"
    spec:
      containers:
        - image: dev.local/fibonacci:1.0.0
          resources:
            requests:
              cpu: 1
              memory: 512M
            limits:
              cpu: 1
              memory: 512M
